server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/volunteer_service?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    #password: Scalpel^80mysql
    password: 111111
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    #password: 111111
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        time-between-eviction-runs: 10s
  mvc:
    static-path-pattern: /**
    pathmatch:
      matching-strategy: ant_path_matcher
  #  web:
#    resources:
#      static-locations: D:\IdeaProjects\volunteer-service\volunteer\target\classes\images

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8




mybatis-plus:
  type-aliases-package: com.volunteer.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:mapper/*.xml

file:
  save:
    #path: /root/data/images
    path: D:\IdeaProjects\volunteer-service\volunteer\src\main\resources\static\images\
